// <auto-generated />
using ApiDindin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiDindin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211018003807_Atualizacao_02")]
    partial class Atualizacao_02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ApiDindin.Models.Aula", b =>
                {
                    b.Property<int>("AulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoAula")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LinkAula")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("TituloAula")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("AulaId");

                    b.ToTable("Aulas");

                    b.HasData(
                        new
                        {
                            AulaId = 1,
                            CursoId = 1,
                            DescricaoAula = "Descrição Aula1",
                            LinkAula = "www.aula.com",
                            TituloAula = "Aula1"
                        },
                        new
                        {
                            AulaId = 2,
                            CursoId = 2,
                            DescricaoAula = "Descrição Aula2",
                            LinkAula = "www.aula.com",
                            TituloAula = "Aula2"
                        },
                        new
                        {
                            AulaId = 3,
                            CursoId = 3,
                            DescricaoAula = "Descrição Aula3",
                            LinkAula = "www.aula.com",
                            TituloAula = "Aula3"
                        });
                });

            modelBuilder.Entity("ApiDindin.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Professor")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UploadCapa")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            Descricao = "Curso teste1",
                            Professor = "Marcos Santos",
                            Titulo = "Titulo 1",
                            UploadCapa = "Capa teste1"
                        },
                        new
                        {
                            CursoId = 2,
                            Descricao = "Curso teste2",
                            Professor = "Luiz Carlos",
                            Titulo = "Titulo 2",
                            UploadCapa = "Capa teste2"
                        },
                        new
                        {
                            CursoId = 3,
                            Descricao = "Curso teste3",
                            Professor = "Regina Sanderberg",
                            Titulo = "Titulo 3",
                            UploadCapa = "Capa teste3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
