// <auto-generated />
using ApiDindin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiDindin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211017212205_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ApiDindin.Models.Aula", b =>
                {
                    b.Property<int>("AulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoAula")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LinkAula")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("TituloAula")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("AulaId");

                    b.ToTable("Aulas");

                    b.HasData(
                        new
                        {
                            AulaId = 1,
                            CursoId = 1,
                            DescricaoAula = "Descrição Aula1",
                            LinkAula = "www.aula.com",
                            TituloAula = "Aula1"
                        },
                        new
                        {
                            AulaId = 2,
                            CursoId = 2,
                            DescricaoAula = "Descrição Aula2",
                            LinkAula = "www.aula.com",
                            TituloAula = "Aula2"
                        },
                        new
                        {
                            AulaId = 3,
                            CursoId = 3,
                            DescricaoAula = "Descrição Aula3",
                            LinkAula = "www.aula.com",
                            TituloAula = "Aula3"
                        });
                });

            modelBuilder.Entity("ApiDindin.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("UploadCapa")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            Descricao = "Curso teste1",
                            Titulo = "Titulo 1",
                            UploadCapa = "Capa teste1"
                        },
                        new
                        {
                            CursoId = 2,
                            Descricao = "Curso teste2",
                            Titulo = "Titulo 2",
                            UploadCapa = "Capa teste2"
                        },
                        new
                        {
                            CursoId = 3,
                            Descricao = "Curso teste3",
                            Titulo = "Titulo 3",
                            UploadCapa = "Capa teste3"
                        });
                });

            modelBuilder.Entity("ApiDindin.Models.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ProfessorId");

                    b.HasIndex("CursoId")
                        .IsUnique();

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            CursoId = 1,
                            Nome = "Paulo Sergio"
                        });
                });

            modelBuilder.Entity("ApiDindin.Models.Professor", b =>
                {
                    b.HasOne("ApiDindin.Models.Curso", null)
                        .WithOne("Professor")
                        .HasForeignKey("ApiDindin.Models.Professor", "CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiDindin.Models.Curso", b =>
                {
                    b.Navigation("Professor");
                });
#pragma warning restore 612, 618
        }
    }
}
